### ISSUE TITLE
Update examples for release 0.2

### ISSUE THREAD

**Issue by zaleslaw** [tensorflow/java-models#17]
Need to switch on release 0.2 and update all examples

**Comment by zaleslaw** [comment]
@karllessard I suggest to switch this repository on the last stable version (0.2.0) not on 0.3.0-SNAPSHOT, what do you think?
We could update and write examples on stable version during development of new one.

**Comment by karllessard** [comment]
> @karllessard I suggest to switch this repository on the last stable version (0.2.0) not on 0.3.0-SNAPSHOT, what do you think?

Yes, I completely agree

> Where is release artifact will be located, what repository should I use?

They are on Maven central so can remove this repository configuration and don’t have to add any other

**Comment by Craigacp** [comment]
We've updated the examples to 1.0.0-rc.2.
