### ISSUE TITLE
Where can I find the API of release 0.2?

### ISSUE THREAD

**Issue by YongXin-Yao** [tensorflow/java-models#20]
https://tensorflow.google.cn/api_docs/java/org/tensorflow/package-summary?authuser=1
This API about old release is deprecated and will be removed in a future version, but I can't find the API about new release.
And my TensorFlow version is 2.2.0, can I use old release(latest version is 1.15) to load model  then use model to predict?

**Comment by Craigacp** [comment]
The TF-Java API docs are hosted here - https://www.tensorflow.org/jvm, though they are currently quite old and we are trying to update them.
