### ISSUE TITLE
The runtime error with protobuf

### ISSUE THREAD

**Issue by zaleslaw** [tensorflow/java-models#6]
Running the CNNMnist or SimpleMnist I catch the next error on my Windows 10 machine.

Looks like incorrect protobuf version in Graph creation: the exception thrown in the next row of code  Graph graph = new Graph();

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/InvalidProtocolBufferException
	at org.tensorflow.model.examples.mnist.CnnMnist.build(CnnMnist.java:80)
	at org.tensorflow.model.examples.mnist.CnnMnist.main(CnnMnist.java:304)
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.InvalidProtocolBufferException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)

**Comment by karllessard** [comment]
What is the version resolved by Maven on your side? Do you explicitly load a different version of protobuf? If not, then it should match the one [from the core API](https://github.com/tensorflow/java/blob/ea00c79506c53b2623cd49f2c090f98a981e6659/tensorflow-core/tensorflow-core-api/pom.xml#L19)

But it seems that it is looking for the exception class itself, which is [super old](https://github.com/protocolbuffers/protobuf/blob/master/java/core/src/main/java/com/google/protobuf/InvalidProtocolBufferException.java), are you sure that protobuf is present in your classpath?

**Comment by saudet** [comment]
You'll need to use the same version of protobuf than the one that was used
to build TF, that's normal...

**Comment by zaleslaw** [comment]
@karllessard my protobuf version is 3.3.1, let's try to load 3.8.0

**Comment by zaleslaw** [comment]
Maybe the problem is the next: it tries to download the examples for legacy-examples

I need to remind, that I has no the Core API TF to build artifacts by hands, I tries to act as a typical user who tries to use these examples

**Comment by zaleslaw** [comment]
I've cleared the Maven cache and the current problem looks like this 
Cannot resolve org.tensorflow:tensorflow-core-platform:0.1.0-SNAPSHOT
Cannot resolve org.tensorflow:tensorflow-training:0.1.0-SNAPSHOT

Because the repository to download is missed, suggest to add next section to the examples POM
  <repositories>
    <repository>
      <id>tensorflow-snapshots</id>
      <url>https://oss.sonatype.org/content/repositories/snapshots/</url>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>

**Comment by karllessard** [comment]
Yeah @zaleslaw , I just realized that as well, the snapshot repo was missing in our example pom.xml, I've [just updated it](https://github.com/tensorflow/java-models/commit/d91770c726734942d8585511df170be31e423e6c) and update the framework dependency while being at it. Can you now give it a try?

**Comment by zaleslaw** [comment]
This work correctly, could be closed now

**Comment by zaleslaw** [comment]
@karllessard closed by mistake, it doesn't work for me well, seems like a common problem with transitive dependencies, that doesn't work for me

**Comment by karllessard** [comment]
@zaleslaw can you give it another shot? We have identified the cause of this problem [(see here)](https://github.com/tensorflow/java-models/issues/4), it should be fine now.

**Comment by zaleslaw** [comment]
Yes, now it's fixed! Great work, guys!
